services:
  postgres:
    image: postgres:16
    container_name: brecho-db
    env_file:
      - .env 
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  webapp:
    container_name: brecho-webapp
    build:
      context: .  
      dockerfile: Dockerfile 
    ports:
      - "8080:80" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: