// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SiteBrecho.Data;

#nullable disable

namespace SiteBrecho.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251106002525_SeedsCompletos")]
    partial class SeedsCompletos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SiteBrecho.Models.AdministradorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Administradores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CriadoEm = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@admin.com",
                            Nome = "Admin",
                            SenhaHash = "123456"
                        });
                });

            modelBuilder.Entity("SiteBrecho.Models.EstoqueModel", b =>
                {
                    b.Property<int>("ProdutoSkuId")
                        .HasColumnType("integer");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean");

                    b.Property<int>("QuantidadeAtual")
                        .HasColumnType("integer");

                    b.HasKey("ProdutoSkuId");

                    b.ToTable("Estoques");

                    b.HasData(
                        new
                        {
                            ProdutoSkuId = 1,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            QuantidadeAtual = 5
                        },
                        new
                        {
                            ProdutoSkuId = 2,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            QuantidadeAtual = 3
                        },
                        new
                        {
                            ProdutoSkuId = 3,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            QuantidadeAtual = 8
                        },
                        new
                        {
                            ProdutoSkuId = 4,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            QuantidadeAtual = 10
                        },
                        new
                        {
                            ProdutoSkuId = 5,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            QuantidadeAtual = 4
                        },
                        new
                        {
                            ProdutoSkuId = 6,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            QuantidadeAtual = 6
                        },
                        new
                        {
                            ProdutoSkuId = 7,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            QuantidadeAtual = 2
                        });
                });

            modelBuilder.Entity("SiteBrecho.Models.FornecedorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CnpjCpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Fornecedores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CnpjCpf = "12.345.678/0001-90",
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Email = "contato@brechodavila.com.br",
                            Endereco = "Rua das Flores, 123 - São Paulo/SP",
                            Excluido = false,
                            Nome = "Brechó da Vila",
                            Telefone = "(11) 98765-4321"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CnpjCpf = "98.765.432/0001-10",
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vendas@vintagestore.com.br",
                            Endereco = "Av. Paulista, 456 - São Paulo/SP",
                            Excluido = false,
                            Nome = "Vintage Store",
                            Telefone = "(11) 91234-5678"
                        });
                });

            modelBuilder.Entity("SiteBrecho.Models.MovimentacaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdministradorId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<int>("ProdutoSkuId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId");

                    b.HasIndex("ProdutoSkuId");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("SiteBrecho.Models.ProdutoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean");

                    b.Property<int?>("FornecedorId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PrecoCusto")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Jaqueta de couro estilo motociclista. Em ótimo estado.",
                            Excluido = false,
                            FornecedorId = 1,
                            Nome = "Jaqueta de Couro Vintage",
                            PrecoCusto = 70.00m,
                            PrecoVenda = 180.50m
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Calça jeans de cintura alta, lavagem clara. Perfeita para um look retrô.",
                            Excluido = false,
                            FornecedorId = 1,
                            Nome = "Calça Jeans Reta Anos 90",
                            PrecoCusto = 25.00m,
                            PrecoVenda = 79.90m
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Vestido longo com estampa floral, ideal para o verão.",
                            Excluido = false,
                            FornecedorId = 2,
                            Nome = "Vestido Floral Longo",
                            PrecoCusto = 35.50m,
                            PrecoVenda = 95.00m
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Bolsa de ombro em couro legítimo, com detalhes em metal dourado.",
                            Excluido = false,
                            FornecedorId = 2,
                            Nome = "Bolsa de Couro Caramelo",
                            PrecoCusto = 50.00m,
                            PrecoVenda = 130.00m
                        });
                });

            modelBuilder.Entity("SiteBrecho.Models.ProdutoSkuModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("ProdutoVariationId1")
                        .HasColumnType("integer");

                    b.Property<int?>("ProdutoVariationId2")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("ProdutoVariationId1");

                    b.HasIndex("ProdutoVariationId2");

                    b.ToTable("ProdutoSkus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Jaqueta M Preta",
                            Excluido = false,
                            PrecoVenda = 180.50m,
                            ProdutoId = 1,
                            ProdutoVariationId1 = 2,
                            ProdutoVariationId2 = 4
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Jaqueta G Preta",
                            Excluido = false,
                            PrecoVenda = 185.00m,
                            ProdutoId = 1,
                            ProdutoVariationId1 = 3,
                            ProdutoVariationId2 = 4
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Calça Jeans P Azul",
                            Excluido = false,
                            PrecoVenda = 79.90m,
                            ProdutoId = 2,
                            ProdutoVariationId1 = 1,
                            ProdutoVariationId2 = 5
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Calça Jeans M Azul",
                            Excluido = false,
                            PrecoVenda = 79.90m,
                            ProdutoId = 2,
                            ProdutoVariationId1 = 2,
                            ProdutoVariationId2 = 5
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Vestido P Vermelho",
                            Excluido = false,
                            PrecoVenda = 95.00m,
                            ProdutoId = 3,
                            ProdutoVariationId1 = 1,
                            ProdutoVariationId2 = 6
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Vestido M Vermelho",
                            Excluido = false,
                            PrecoVenda = 95.00m,
                            ProdutoId = 3,
                            ProdutoVariationId1 = 2,
                            ProdutoVariationId2 = 6
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Bolsa Tamanho M",
                            Excluido = false,
                            PrecoVenda = 130.00m,
                            ProdutoId = 4,
                            ProdutoVariationId1 = 2
                        });
                });

            modelBuilder.Entity("SiteBrecho.Models.ProdutoVariationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ProdutoVariations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Pequeno",
                            Excluido = false,
                            Nome = "Tamanho P"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Médio",
                            Excluido = false,
                            Nome = "Tamanho M"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Grande",
                            Excluido = false,
                            Nome = "Tamanho G"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            Nome = "Cor Preta"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            Nome = "Cor Azul"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            Nome = "Cor Vermelha"
                        });
                });

            modelBuilder.Entity("SiteBrecho.Models.VendaItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoSkuId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int?>("VendaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoSkuId");

                    b.HasIndex("VendaId");

                    b.ToTable("VendaItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            PrecoUnitario = 180.50m,
                            ProdutoSkuId = 1,
                            Quantidade = 1,
                            VendaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            PrecoUnitario = 79.90m,
                            ProdutoSkuId = 3,
                            Quantidade = 1,
                            VendaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            PrecoUnitario = 95.00m,
                            ProdutoSkuId = 5,
                            Quantidade = 1,
                            VendaId = 2
                        });
                });

            modelBuilder.Entity("SiteBrecho.Models.VendaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Vendas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            DataVenda = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            NomeCliente = "Maria Silva",
                            ValorTotal = 275.40m
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            CriadoEm = new DateTime(2025, 9, 2, 20, 0, 0, 0, DateTimeKind.Utc),
                            DataVenda = new DateTime(2025, 9, 3, 20, 0, 0, 0, DateTimeKind.Utc),
                            Excluido = false,
                            NomeCliente = "João Santos",
                            ValorTotal = 95.00m
                        });
                });

            modelBuilder.Entity("SiteBrecho.Models.EstoqueModel", b =>
                {
                    b.HasOne("SiteBrecho.Models.ProdutoSkuModel", "ProdutoSku")
                        .WithOne()
                        .HasForeignKey("SiteBrecho.Models.EstoqueModel", "ProdutoSkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProdutoSku");
                });

            modelBuilder.Entity("SiteBrecho.Models.MovimentacaoModel", b =>
                {
                    b.HasOne("SiteBrecho.Models.AdministradorModel", "Administrador")
                        .WithMany()
                        .HasForeignKey("AdministradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiteBrecho.Models.ProdutoSkuModel", "ProdutoSku")
                        .WithMany()
                        .HasForeignKey("ProdutoSkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrador");

                    b.Navigation("ProdutoSku");
                });

            modelBuilder.Entity("SiteBrecho.Models.ProdutoSkuModel", b =>
                {
                    b.HasOne("SiteBrecho.Models.ProdutoModel", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiteBrecho.Models.ProdutoVariationModel", "Variacao1")
                        .WithMany()
                        .HasForeignKey("ProdutoVariationId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiteBrecho.Models.ProdutoVariationModel", "Variacao2")
                        .WithMany()
                        .HasForeignKey("ProdutoVariationId2");

                    b.Navigation("Produto");

                    b.Navigation("Variacao1");

                    b.Navigation("Variacao2");
                });

            modelBuilder.Entity("SiteBrecho.Models.VendaItemModel", b =>
                {
                    b.HasOne("SiteBrecho.Models.ProdutoSkuModel", "ProdutoSku")
                        .WithMany()
                        .HasForeignKey("ProdutoSkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiteBrecho.Models.VendaModel", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaId");

                    b.Navigation("ProdutoSku");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("SiteBrecho.Models.VendaModel", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
